import React, { useEffect, useState } from "react";
import { MessageCircle, FileDown, ChevronDown, ChevronUp, Plus, Minus, Trash2 } from "lucide-react";
import { supabase } from "../lib/supabase";
import { loadPricingRules, agruparPorProducto, PricingRule, LineaPedido } from "../lib/pricing";
import { generarPdfGrande } from "../lib/pdf";

interface ItemDia extends LineaPedido { orderId: string; orderStatus: string; }
interface Fila { customerId: string; nombre: string; telefono: string; items: ItemDia[]; }

export default function ReportesDelDia() {
  const [filas, setFilas] = useState<Fila[]>([]); const [reglas, setReglas] = useState<PricingRule[]>([]);
  const [nombreNegocio, setNombreNegocio] = useState("Loves Stories"); const [expandido, setExpandido] = useState<string | null>(null);
  const [generando, setGenerando] = useState<string | null>(null); const [editando, setEditando] = useState<string | null>(null);
  useEffect(() => { cargar(); loadPricingRules().then(setReglas); supabase.from("app_settings").select("business_name").eq("id",1).single().then(({data})=>{if(data?.business_name)setNombreNegocio(data.business_name);}); }, []);

  async function cargar() {
    const hoy=new Date(); hoy.setHours(0,0,0,0);
    const {data,error}=await supabase.from("order_items").select("id, order_id, product_id, quantity, unit_price, assigned_at, orders(customer_id,status,customers(name,phone)), products(code,name,category_id,image_url)").gte("assigned_at",hoy.toISOString());
    if(error){alert(error.message);return;}
    const agrupado:Record<string,Fila>={};
    (data??[]).forEach((it:any)=>{const cid=it.orders?.customer_id;if(!cid)return;if(!agrupado[cid])agrupado[cid]={customerId:cid,nombre:it.orders.customers?.name??"Cliente",telefono:it.orders.customers?.phone??"",items:[]}; agrupado[cid].items.push({id:it.id,orderId:it.order_id,orderStatus:it.orders?.status??"open",product_id:it.product_id,codigo:it.products?.code??"",nombre:it.products?.name??"",categoria_id:it.products?.category_id??null,cantidad:it.quantity,precio_base:it.unit_price,imagen:it.products?.image_url??null,fecha:new Date(it.assigned_at).toLocaleTimeString("es-BO").slice(0,5)});});
    setFilas(Object.values(agrupado));
  }
  async function finalizarCorreccion(item:ItemDia){ if(item.orderStatus==="closed"){ const {error}=await supabase.rpc("recalcular_total_venta",{p_order_id:item.orderId}); if(error)throw new Error(error.message); const {error:e2}=await supabase.rpc("rebuild_customer_payment_applications",{p_customer_id:filas.find(f=>f.items.some(x=>x.id===item.id))?.customerId}); if(e2)throw new Error(e2.message); } }
  async function cambiar(item:ItemDia,delta:number){ if(editando)return; setEditando(item.id); try{ if(delta<0){const {error}=await supabase.rpc("remove_order_item_unit",{p_order_item_id:item.id,p_quantity:1});if(error)throw new Error(error.message);}else{const {error}=await supabase.rpc("assign_product_to_order",{p_order_id:item.orderId,p_product_id:item.product_id,p_quantity:1,p_origin:"correccion"});if(error)throw new Error(error.message);} await finalizarCorreccion(item); await cargar();}catch(e:any){alert(`No se pudo corregir: ${e.message}`);}finally{setEditando(null);} }
  async function eliminar(item:ItemDia){if(!confirm(`¿Eliminar ${item.cantidad} unidad(es) de ${item.codigo}? Volverán al inventario.`))return;if(editando)return;setEditando(item.id);try{const {error}=await supabase.rpc("remove_order_item_unit",{p_order_item_id:item.id,p_quantity:item.cantidad});if(error)throw new Error(error.message);await finalizarCorreccion(item);await cargar();}catch(e:any){alert(`No se pudo eliminar: ${e.message}`);}finally{setEditando(null);} }
  function linkWhatsapp(f:Fila,total:number){const detalle=f.items.map(it=>`${it.codigo} x${it.cantidad}`).join(", ");return `https://wa.me/${f.telefono.replace(/\D/g,"")}?text=${encodeURIComponent(`Hola ${f.nombre}. Hoy se agregó a tu pedido en ${nombreNegocio}: ${detalle}. Total agregado hoy: Bs ${total.toFixed(2)}.`)}`;}
  async function generarPdfDiario(f:Fila){const grupos=agruparPorProducto(reglas,f.items),sub=grupos.reduce((a,g)=>a+g.subtotalSinDescuento,0),total=grupos.reduce((a,g)=>a+g.subtotalConDescuento,0);setGenerando(f.customerId);await generarPdfGrande({negocio:nombreNegocio,cliente:f.nombre,telefono:f.telefono,fecha:new Date().toLocaleDateString("es-BO"),titulo:"Detalle del día",grupos,subtotalSinDescuento:sub,descuentoTotal:sub-total,total,depositado:0,saldoPendiente:0,saldoAFavor:0,mostrarPagos:false});setGenerando(null);}
  return <div><p className="font-serif text-lg mb-1">Reportes del día</p><p className="text-xs mb-3" style={{color:"#5B4E5E"}}>Puedes corregir cantidades del día. Al disminuir/eliminar vuelve stock; al aumentar se descuenta. Si la venta estaba cerrada, también se recalculan total y saldo.</p><div style={{background:"#F7F3EC",border:"1px solid #D9D0C2"}}>{filas.length===0&&<p className="text-sm p-4">Nadie tiene ítems asignados hoy todavía.</p>}{filas.map((f,i)=>{const grupos=agruparPorProducto(reglas,f.items),total=grupos.reduce((a,g)=>a+g.subtotalConDescuento,0),abierto=expandido===f.customerId;return <div key={f.customerId} style={{borderBottom:i<filas.length-1?"1px solid #D9D0C2":"none"}}><div className="flex items-center justify-between px-3.5 py-3"><button onClick={()=>setExpandido(abierto?null:f.customerId)} className="flex items-center gap-2 text-left flex-1">{abierto?<ChevronUp size={14}/>:<ChevronDown size={14}/>}<div><p className="text-sm">{f.nombre}</p><p className="text-xs" style={{color:"#5B4E5E"}}>{f.telefono} · Bs {total.toFixed(2)} agregado hoy</p></div></button><div className="flex gap-1.5"><button onClick={()=>generarPdfDiario(f)} className="text-xs px-2.5 py-1.5 rounded-md flex gap-1"><FileDown size={12}/>PDF diario</button><a href={linkWhatsapp(f,total)} target="_blank" rel="noreferrer" className="text-xs px-2.5 py-1.5 rounded-md flex gap-1" style={{background:"#9C7A3C",color:"#F7F3EC"}}><MessageCircle size={12}/>WhatsApp</a></div></div>{abierto&&<div className="px-3.5 pb-3" style={{background:"#EDE7DE"}}>{f.items.map(it=><div key={it.id} className="flex items-center justify-between text-xs py-2" style={{borderBottom:"1px solid #D9D0C2"}}><span>{it.codigo} · {it.nombre} × {it.cantidad} · Bs {Number(it.precio_base).toFixed(2)} c/u</span><div className="flex items-center gap-1"><button disabled={editando===it.id} onClick={()=>cambiar(it,-1)} className="p-1.5 rounded" style={{background:"#F7F3EC"}}><Minus size={12}/></button><button disabled={editando===it.id} onClick={()=>cambiar(it,1)} className="p-1.5 rounded" style={{background:"#F7F3EC"}}><Plus size={12}/></button><button disabled={editando===it.id} onClick={()=>eliminar(it)} className="p-1.5 rounded" style={{background:"#F4E3E6",color:"#7A2540"}}><Trash2 size={12}/></button></div></div>)}</div>}</div>})}</div></div>;
}
