import React,{useEffect,useState} from "react";
import { FileDown } from "lucide-react";
import { jsPDF } from "jspdf";
import {supabase} from "../lib/supabase";

export default function HistorialClientes(){
 const [clientes,setClientes]=useState<any[]>([]),[id,setId]=useState(""),[datos,setDatos]=useState<any>({orders:[],payments:[],returns:[]});
 useEffect(()=>{supabase.from('customers').select('id,name,phone').is('deleted_at',null).order('name').then(({data})=>{setClientes(data??[]);if(data?.[0])setId(data[0].id)})},[]); useEffect(()=>{if(id)cargar()},[id]);
 async function cargar(){const [o,p,r]=await Promise.all([supabase.from('orders').select('id,order_number,status,opened_at,closed_at,total_cerrado,order_items(quantity,unit_price,products(code,name))').eq('customer_id',id).order('opened_at',{ascending:false}),supabase.from('payments').select('amount,method,notes,paid_at,order_id').eq('customer_id',id).order('paid_at',{ascending:false}),supabase.from('returns').select('total_amount,reason,type,created_at,order_id,status').eq('customer_id',id).order('created_at',{ascending:false})]);setDatos({orders:o.data??[],payments:p.data??[],returns:r.data??[]})}
 function pdfCuenta(o:any){const c=clientes.find(x=>x.id===id);const doc=new jsPDF({unit:'mm',format:'a4'});let y=18;doc.setFont('times','bolditalic');doc.setTextColor(156,122,60);doc.setFontSize(22);doc.text("Loves Stories",15,y);y+=10;doc.setTextColor(30,30,30);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text('Historial de cuenta del cliente',15,y);y+=9;doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text(`Cliente: ${c?.name??''}`,15,y);y+=5;doc.text(`Teléfono: ${c?.phone??''}`,15,y);y+=5;doc.text(`Fecha de apertura: ${new Date(o.opened_at).toLocaleString('es-BO')}`,15,y);y+=5;doc.text(`Fecha de cierre: ${o.closed_at?new Date(o.closed_at).toLocaleString('es-BO'):'Cuenta abierta'}`,15,y);y+=8;doc.line(15,y,195,y);y+=7;doc.setFont('helvetica','bold');doc.text('CANT.',15,y);doc.text('CÓDIGO',32,y);doc.text('PRODUCTO',62,y);doc.text('IMPORTE',195,y,{align:'right'});y+=5;doc.setFont('helvetica','normal');for(const x of o.order_items??[]){if(y>275){doc.addPage();y=18}const imp=Number(x.quantity||0)*Number(x.unit_price||0);doc.text(String(x.quantity),15,y);doc.text(String(x.products?.code??''),32,y);doc.text(String(x.products?.name??''),62,y,{maxWidth:85});doc.text(`Bs ${imp.toFixed(2)}`,195,y,{align:'right'});y+=6}y+=3;doc.line(15,y,195,y);y+=7;doc.setFont('helvetica','bold');doc.text('TOTAL',15,y);doc.text(`Bs ${Number(o.total_cerrado??0).toFixed(2)}`,195,y,{align:'right'});y+=8;doc.setFont('helvetica','normal');doc.text(`Pagos: ${datos.payments.filter((p:any)=>p.order_id===o.id).map((p:any)=>`Bs ${Number(p.amount).toFixed(2)} ${p.method}`).join(' · ')||'—'}`,15,y,{maxWidth:180});doc.save(`historial_${(c?.name??'cliente').replace(/\s+/g,'_')}_${o.order_number??''}.pdf`)}
 return <div><p className="font-serif text-lg mb-3">Historial completo del cliente</p><select value={id} onChange={e=>setId(e.target.value)} className="w-full max-w-md px-3 py-2 rounded mb-4">{clientes.map(c=><option value={c.id} key={c.id}>{c.name} · {c.phone}</option>)}</select>
 {datos.orders.map((o:any)=><div key={o.id} className="p-3 mb-2 rounded" style={{background:'#F7F3EC',border:'1px solid #D9D0C2'}}><div className="flex justify-between gap-2"><div><p className="text-sm font-medium">Pedido #{o.order_number} · {o.status==='closed'?'Cerrado':'Abierto'} · Bs {Number(o.total_cerrado??0).toFixed(2)}</p><p className="text-xs" style={{color:'#5B4E5E'}}>Fecha de apertura: {new Date(o.opened_at).toLocaleString('es-BO')} · Fecha de cierre: {o.closed_at ? new Date(o.closed_at).toLocaleString('es-BO') : 'Cuenta abierta'}</p></div><button onClick={()=>pdfCuenta(o)} className="text-xs px-3 py-2 rounded-md flex items-center gap-1" style={{background:'#9C7A3C',color:'white'}}><FileDown size={14}/>PDF</button></div><p className="text-xs mt-2">{o.order_items?.map((x:any)=>`${x.products?.code} ${x.products?.name} ×${x.quantity} (Bs ${x.unit_price})`).join(' · ')||'Sin items'}</p><div className="text-xs mt-2">Pagos: {datos.payments.filter((p:any)=>p.order_id===o.id).map((p:any)=>`Bs ${p.amount} ${p.method}`).join(' · ')||'—'}</div><div className="text-xs" style={{color:'#7A2540'}}>Devoluciones: {datos.returns.filter((r:any)=>r.order_id===o.id&&r.status==='activa'&&r.type==='producto').map((r:any)=>`Bs ${r.total_amount} ${r.reason}`).join(' · ')||'—'}</div></div>)}</div>
}
